version: "3.8"

services:
  mariadb:
    image: mariadb
    container_name: cardfillingbot-db
    volumes:
      - ./mariadb/CardFillingBot-0-dumpwithdata.sql:/docker-entrypoint-initdb.d/CardFillingBot-0-dumpwithdata.sql
      # - ./mariadb/CardFillingBot-4-testingscope.sql:/docker-entrypoint-initdb.d/CardFillingBot-4-testingscope.sql
    environment:
      - MARIADB_ALLOW_EMPTY_ROOT_PASSWORD=yes
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - TZ=${TZ}
  redis:
    build:
      dockerfile: Dockerfile-redis
      context: .
    image: nkuznetsov44/cardfillingbot-redis
    container_name: cardfillingbot-redis
    volumes:
      - ./redis/redis-dev.conf:/usr/local/etc/redis/redis.conf
  cardfillingbot:
    build:
      dockerfile: Dockerfile-cardfillingbot
      context: .
    image: nkuznetsov44/cardfillingbot
    container_name: cardfillingbot
    depends_on:
      - mariadb
      - redis
    restart: on-failure
    environment:
      - TELEGRAM_TOKEN=${TELEGRAM_TOKEN}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_HOST=${MYSQL_HOST}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_DB=0
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - TZ=${TZ}
      - LOG_LEVEL=${LOG_LEVEL}
      - ADMIN_USER_ID=${ADMIN_USER_ID}
