version: "3.8"

services:
  mariadb:
    image: mariadb
    container_name: cardfillingbot-db
    volumes:
      - ./mariadb/dump.sql:/docker-entrypoint-initdb.d/CardFillingBot-0-dumpwithdata.sql
      - ./mariadb/CardFillingBot-4-testingscope.sql:/docker-entrypoint-initdb.d/CardFillingBot-4-testingscope.sql
    environment:
      - MARIADB_ALLOW_EMPTY_ROOT_PASSWORD=yes
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - TZ=${TZ}
    ports:
      - 3306:3306
  redis:
    build:
      dockerfile: Dockerfile-redis
      context: .
    image: nkuznetsov44/cardfillingbot-redis
    container_name: cardfillingbot-redis
    volumes:
      - ./redis/redis-dev.conf:/usr/local/etc/redis/redis.conf
    ports:
      - 6379:6379
