version: "3.8"

services:
  mariadb:
    image: mariadb
    container_name: cardfillingbot-mariadb-${ENVIRONMENT}
    volumes:
      # - ./card_filling_bot/mariadb/CardFillingBot-1-schema.sql:/docker-entrypoint-initdb.d/CardFillingBot-1-schema.sql
      # - ./card_filling_bot/mariadb/CardFillingBot-2-categories.sql:/docker-entrypoint-initdb.d/CardFillingBot-2-categories.sql
      - ./mariadb/CardFillingBot-0-dumpwithdata.sql:/docker-entrypoint-initdb.d/CardFillingBot-0-dumpwithdata.sql
      - ./mariadb/CardFillingBot-3-user.sql:/docker-entrypoint-initdb.d/CardFillingBot-3-user.sql
      - ./mariadb/CardFillingBot-4-testingscope.sql:/docker-entrypoint-initdb.d/CardFillingBot-4-testingscope.sql
    environment:
      - MARIADB_ALLOW_EMPTY_ROOT_PASSWORD=yes
      - MARIADB_DATABASE=CardFillingBot
    ports:
      - 3306:3306
  redis:
    build:
      dockerfile: Dockerfile-redis
      context: .
    image: nkuznetsov44/cardfillingbot-redis:${ENVIRONMENT}
    container_name: cardfillingbot-redis-${ENVIRONMENT}
    volumes:
      - ./redis/redis-dev.conf:/usr/local/etc/redis/redis.conf
    ports:
      - 6379:6379