FROM python:3.9.7-alpine

# add packages for matplotlib
RUN apk add g++ jpeg-dev zlib-dev libjpeg make

# set environment variables
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

# install dependencies
RUN pip install --upgrade pip
COPY ./requirements.txt .
RUN pip install -r requirements.txt

# copy project
COPY ./card_filling_bot ./card_filling_bot
COPY ./telegramapi ./card_filling_bot/telegramapi

WORKDIR /card_filling_bot

CMD ["gunicorn", "--bind", ":8000", "wsgi:app"]