FROM python:3.9.7-alpine

# add packages for matplotlib
RUN apk add g++ jpeg-dev zlib-dev libjpeg make

# set environment variables
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

# install dependencies
RUN pip install --upgrade pip
COPY ./requirements.txt .
RUN pip install -r requirements.txt

# copy project
COPY . .
WORKDIR .

CMD ["python3", "card_filling_bot.py"]