FROM python:3.11-alpine

RUN apk add g++ jpeg-dev zlib-dev libjpeg make

ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

RUN pip install --upgrade pip
COPY ./requirements.txt .
RUN pip install -r requirements.txt

COPY . .
WORKDIR .

CMD ["gunicorn", "-c", "gunicorn.conf.py", "web_app:app"]
