apiVersion: v1
kind: ConfigMap
metadata:
    name: cardfillingbot-config
data:
    redis-config: |
        port 6379
        maxmemory 100mb
        maxmemory-policy allkeys-lru
        requirepass cardfillingbot