apiVersion: apps/v1
kind: Deployment
metadata:
  name: cardfillingbot
  labels:
    app: cardfillingbot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cardfillingbot
  template:
    metadata:
      labels:
        app: cardfillingbot
    spec:
      containers:
      - name: cardfillingbot
        image: nkuznetsov44/cardfillingbot:x86prod
        imagePullPolicy: Always
        ports:
        - containerPort: 8000
        env:
        - name: TELEGRAM_TOKEN
          valueFrom:
            secretKeyRef:
              name: cardfillingbot-secrets
              key: TELEGRAM_TOKEN
        - name: MYSQL_USER
          valueFrom:
            secretKeyRef:
              name: cardfillingbot-secrets
              key: MYSQL_USER
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: cardfillingbot-secrets
              key: MYSQL_PASSWORD
        - name: MYSQL_HOST
          valueFrom:
            secretKeyRef:
              name: cardfillingbot-secrets
              key: MYSQL_HOST
        - name: MYSQL_DATABASE
          valueFrom:
            secretKeyRef:
              name: cardfillingbot-secrets
              key: MYSQL_DATABASE
        - name: REDIS_HOST
          valueFrom:
            secretKeyRef:
              name: cardfillingbot-secrets
              key: REDIS_HOST
        - name: REDIS_DB
          valueFrom:
            secretKeyRef:
              name: cardfillingbot-secrets
              key: REDIS_DB
        - name: REDIS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: cardfillingbot-secrets
              key: REDIS_PASSWORD
        - name: WEBHOOK_HOST
          valueFrom:
            secretKeyRef:
              name: cardfillingbot-secrets
              key: WEBHOOK_HOST
        - name: WEBHOOK_PATH
          valueFrom:
            secretKeyRef:
              name: cardfillingbot-secrets
              key: WEBHOOK_PATH
        - name: WEBAPP_HOST
          valueFrom:
            secretKeyRef:
              name: cardfillingbot-secrets
              key: WEBAPP_HOST
        - name: WEBAPP_PORT
          valueFrom:
            secretKeyRef:
              name: cardfillingbot-secrets
              key: WEBAPP_PORT
        - name: SCHEDULER_CLEAR_JOBS
          valueFrom:
            secretKeyRef:
              name: cardfillingbot-secrets
              key: SCHEDULER_CLEAR_JOBS
        - name: MINOR_PROPORTION_USER_ID
          valueFrom:
            secretKeyRef:
              name: cardfillingbot-secrets
              key: MINOR_PROPORTION_USER_ID
        - name: MAJOR_PROPORTION_USER_ID
          valueFrom:
            secretKeyRef:
              name: cardfillingbot-secrets
              key: MAJOR_PROPORTION_USER_ID
        - name: LOG_LEVEL
          valueFrom:
            secretKeyRef:
              name: cardfillingbot-secrets
              key: LOG_LEVEL
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cardfillingbot-redis
  labels:
    app: cardfillingbot-redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cardfillingbot-redis
  template:
    metadata:
      labels:
        app: cardfillingbot-redis
    spec:
      containers:
      - name: cardfillingbot-redis
        image: redis
        command:
          - redis-server
          - "/usr/local/etc/redis.conf"
        ports:
          - containerPort: 6379
        volumeMounts:
          - mountPath: /usr/local/etc
            name: config
      volumes:
        - name: config
          configMap:
            name: cardfillingbot-config
            items:
              - key: redis-config
                path: redis.conf